In [1]:
import numpy as np
from sklearn.datasets import load_iris,make_classification
import matplotlib.pyplot as plt

In [2]:
data = load_iris()

In [3]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data[data.target!=2]
X = np.insert(X, 4, 1, axis=1)

In [5]:
Y = data.target[data.target!=2]
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
Y = Y.reshape((-1,1))

In [ ]:
class LogisticRegression():
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
        
    def update(self, X, y):
        temp = np.zeros((X.shape[1],1))
        for i in range(X.shape[0]):
            temp += (X[i]*(np.exp(X[i]@self.w)/(1+np.exp(X[i]@self.w))-Y[i])).reshape((-1,1))
        self.w -= 0.01*temp
        
    def fit(self, X, y):
        self.w = np.random.randn(X.shape[1], 1)
        for i in range(100):
            self.update(X, y)
            y_pred = self.sigmoid(X @ self.w)
            print(np.mean(0.5*(y_pred-y)**2))
            
            
    def predict(self, X):
        y_pred = np.round(self.sigmoid(X @ self.w))
        return y_pred  

参数的更新也可简写成 **w -= 0.01 * X.T @ (y_pred - y)**，和update()的效果一样

In [8]:
classifier = LogisticRegression()

In [9]:
classifier.fit(X,Y)

0.24999999410725782
0.04287033203393673
0.062291928510974225
0.24947031139567932
0.24999954084785628
0.013827234402155658
0.027346622850956893
0.036282779842670504
0.1378659938826815
0.24669790981898135
0.24994787632097712
0.005555229489583916
0.00012064832583687861
8.142697799719274e-05
5.9895203017584326e-05
4.668165916727602e-05
3.7953650259373034e-05
3.187820195101738e-05
2.747979316889556e-05
2.4196860544215375e-05
2.1686019719972937e-05
1.9726972740159842e-05
1.8172750868240263e-05
1.6922072089820002e-05
1.5903206623564616e-05
1.506415984426374e-05
1.4366483072572921e-05
1.3781249690926683e-05
1.328636766095004e-05
1.2864741437214161e-05
1.2502987981742575e-05
1.2190522747872069e-05
1.1918897911311408e-05
1.1681315869638575e-05
1.147226663482555e-05
1.1287254186045458e-05
1.1122587620955714e-05
1.0975220128697187e-05
1.084262368184428e-05
1.0722690702565394e-05
1.0613656305461947e-05
1.0514036382456363e-05
1.0422577988120535e-05
1.0338219349877693e-05
1.0260057463174727e-05
1.018

In [10]:
y_pred = classifier.predict(X)
y_pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [11]:
accuracy = np.sum(Y == y_pred, axis=0) / len(Y)

In [12]:
accuracy

array([1.])